sonar.projectKey=orkeilius_nook_camp
sonar.organization=orkeilius


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=nook_camp
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.rust.lcov.reportPaths=lcov.info

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8